# Generated by Django 5.1.5 on 2025-02-02 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, unique=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Comment', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(max_length=255, verbose_name='Post Information')),
                ('Image', models.ImageField(default='blog/images/default.jpg', upload_to='Post/images', verbose_name='Post Image')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Create time of Post')),
                ('Updated', models.DateTimeField(auto_now=True, verbose_name='Update time of Post')),
                ('Author', models.ForeignKey(default='0150171080', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Posts', to='Post.category')),
                ('Social', models.ManyToManyField(null=True, to='Post.social', verbose_name='Post Social Address')),
                ('Tag', models.ManyToManyField(null=True, to='Post.tag', verbose_name='Post Content')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'Post',
            },
        ),
    ]
