# Generated by Django 5.1.5 on 2025-02-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaddress',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialaddress',
            name='Comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
