# Generated by Django 5.1.5 on 2025-02-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_socialaddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaddress',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
