# Generated by Django 5.1.5 on 2025-02-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_socialaddress_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Social',
        ),
        migrations.AddField(
            model_name='socialaddress',
            name='Post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.post'),
        ),
    ]
