# Generated by Django 5.1.5 on 2025-02-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_remove_post_social_socialaddress_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Comment',
            field=models.TextField(verbose_name='Post Information'),
        ),
    ]
