# Generated by Django 5.1.5 on 2025-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_alter_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Title',
            field=models.CharField(default='None', max_length=100, unique=True),
        ),
    ]
