# Generated by Django 5.1.5 on 2025-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Banner',
            field=models.ImageField(blank=True, null=True, upload_to='Post/images', verbose_name='Post Banner'),
        ),
    ]
