# Generated by Django 5.1.5 on 2025-02-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_alter_socialaddress_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Tag',
            field=models.ManyToManyField(related_name='Tags', to='Post.posttag', verbose_name='Post Content'),
        ),
    ]
