# Generated by Django 5.1.5 on 2025-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Tag',
            field=models.ManyToManyField(related_name='Posts', to='Post.posttag', verbose_name='Post Content'),
        ),
    ]
