# Generated by Django 5.1.5 on 2025-02-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_remove_comment_reply_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Replies', to='Post.comment'),
        ),
    ]
