# Generated by Django 5.1.5 on 2025-02-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Body',
            field=models.TextField(unique=True),
        ),
    ]
