# Generated by Django 5.1.5 on 2025-02-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0018_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Body',
            field=models.TextField(),
        ),
    ]
