# Generated by Django 5.1.5 on 2025-01-20 17:23

import account_app.validator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('UserName', models.CharField(db_column='نام کاربری', help_text='فیلد اجباری*. نام کاربری کاربر را بنویسید', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='نام کاربری')),
                ('Password', models.CharField(db_column='رمز عبور', help_text='فیلد اجباری*. رمز عبور کاربر را بنویسید', max_length=100, verbose_name='رمز عبور')),
                ('FirstName', models.CharField(db_column='نام', help_text='فیلد اجباری*. نام کاربر را بنویسید', max_length=100, verbose_name='نام')),
                ('LastName', models.CharField(db_column='نام خانوادگی', help_text='فیلد اجباری*. نام خانوادگی کاربر را بنویسید', max_length=100, verbose_name='نام خانوادگی')),
                ('NationalCode', models.CharField(blank=True, db_column='کد ملی', help_text='فیلد اجباری*. کد ملی کاربر را بنویسید', max_length=10, null=True, unique=True, validators=[account_app.validator.Validator.NationalCode_Validator], verbose_name='کد ملی')),
                ('BirthDate', models.DateField(blank=True, db_column='تاریخ تولد', help_text='تاریخ تولد کاربر را بنویسید', null=True, verbose_name='تاریخ تولد')),
                ('Gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], db_column='جنسیت', help_text='فیلد اجباری*. جنسیت کاربر را بنویسید', max_length=6, verbose_name='جنسیت')),
                ('About', models.CharField(blank=True, db_column='درباره من', help_text='درباره کاربر بنویسید', max_length=500, null=True, verbose_name='درباره من')),
                ('FatherName', models.CharField(blank=True, db_column='نام پدر', help_text='نام پدر کاربر را بنویسید', max_length=100, null=True, verbose_name='نام پدر')),
                ('Image', models.ImageField(blank=True, db_column='عکس', help_text='عکس کاربر را وارد کنید', null=True, upload_to='accounts/profile-images', verbose_name='عکس کاربر')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_column='نام دین', help_text='نام دین را بنویسید', max_length=50, verbose_name='نام دین')),
            ],
            options={
                'verbose_name': 'دین',
                'verbose_name_plural': 'ادیان',
                'db_table': 'Religion',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TelNumber', models.CharField(db_column='شماره تماس', help_text='شماره تماس کاربر را بنویسید', max_length=11, verbose_name='شماره تماس')),
                ('Type', models.CharField(blank=True, choices=[('Phone', 'phone'), ('Home', 'home'), ('Work', 'work'), ('School', 'school')], db_column='نوع شماره تماس', help_text='نوع شماره تماس کاربر را بنویسید', max_length=6, null=True, verbose_name='نوع شماره تماس')),
                ('IsDefault', models.BooleanField(db_column='شماره تماس پیش فرض', default=True, help_text='بگویید که آیا این شماره تماس پیش فرض کاربر است یا خیر', verbose_name='آیا پیش فرض است؟')),
                ('User', models.ForeignKey(db_column='کاربر', help_text='شماره تماس کدام کاربر است', on_delete=django.db.models.deletion.CASCADE, related_name='phoneNumbers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره های تماس',
                'db_table': 'PhoneNumber',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='Religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Users', to='account_app.religion'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_column='سمت', help_text='سمت کاربر را بنویسید', max_length=50, verbose_name='سمت کاربر')),
                ('User', models.ForeignKey(db_column='کاربر', help_text='سمت کدام کاربر است', on_delete=django.db.models.deletion.CASCADE, related_name='Roles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سمت',
                'verbose_name_plural': 'سمت ها',
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(db_column='ایمیل', help_text='ایمیل کاربر را بنویسید', max_length=254, verbose_name='آدرس پست الکترونیکی')),
                ('Type', models.CharField(blank=True, choices=[('Phone', 'phone'), ('Home', 'home'), ('Work', 'work'), ('School', 'school')], db_column='نوع ایمیل', help_text='نوع ایمیل کاربر را بنویسید', max_length=6, null=True, verbose_name='نوع ایمیل')),
                ('Is_Default', models.BooleanField(db_column='ایمیل پیش فرض', default=True, help_text='بگویید که آیا این ایمیل پیش فرض کاربر است یا خیر', verbose_name='آیا پیش فرض است؟')),
                ('User', models.ForeignKey(db_column='کاربر', help_text='ایمیل کدام کاربر است', on_delete=django.db.models.deletion.CASCADE, related_name='Emails', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس پست الکترونیکی',
                'verbose_name_plural': 'آدرس های پست الکترونیکی',
                'db_table': 'EmailAddress',
                'unique_together': {('User', 'Email')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together={('FirstName', 'LastName')},
        ),
    ]
