# Generated by Django 5.0.2 on 2024-12-10 14:46

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('name', models.CharField(db_column='First_Name', db_comment='First Name of person', default='Johan', help_text='enter person first name on this field', max_length=50, verbose_name='First Name')),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True)),
                ('nationalCode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code=None, flags=None, inverse_match=None, message='National Code Have to be 10 length of Numbers', regex='^\\d{10}$')])),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('shirtNumber', models.PositiveSmallIntegerField(help_text='The Number That Shows in Player T-shirt', unique_for_year='pub_date')),
            ],
            options={
                'verbose_name': 'Football Player',
                'verbose_name_plural': 'Football Players',
                'db_table': 'Football Player',
                'unique_together': {('name', 'shirtNumber')},
            },
        ),
    ]
