# Generated by Django 5.1.5 on 2025-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(db_column='رمز عبور', help_text='فیلد اجباری*. رمز عبور کاربر را بنویسید', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserName',
            field=models.CharField(db_column='نام کاربری', help_text='فیلد اجباری*. نام کاربری کاربر را بنویسید', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
