# Generated by Django 5.0.2 on 2024-12-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
