# Generated by Django 5.0.2 on 2025-01-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_test_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nCode',
            field=models.CharField(default=0, max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
