# Generated by Django 5.0.2 on 2024-12-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='Article Tag'),
        ),
    ]
