# Generated by Django 5.1.5 on 2025-01-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_category_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتوا ها',
            },
        ),
    ]
