# Generated by Django 5.1.5 on 2025-01-19 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['created'], 'verbose_name': 'محتوا', 'verbose_name_plural': 'محتوا ها'},
        ),
        migrations.AddField(
            model_name='content',
            name='created',
            field=models.DateField(default=datetime.date(2025, 1, 19)),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
