# Generated by Django 5.1.5 on 2025-01-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_content_options_content_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
