# Generated by Django 5.1.5 on 2025-01-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_remove_article_title_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='blog/images/default.jfif', upload_to='blog/images', verbose_name='Article Image'),
        ),
    ]
