# Generated by Django 5.1.5 on 2025-01-22 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('UserName', models.CharField(db_column='نام کاربری', help_text='فیلد اجباری*. نام کاربری کاربر را بنویسید', max_length=100, unique=True, verbose_name='نام کاربری')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('temp_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('FirstName', models.CharField(db_column='نام', help_text='فیلد اجباری*. نام کاربر را بنویسید', max_length=100, verbose_name='نام')),
                ('LastName', models.CharField(db_column='نام خانوادگی', help_text='فیلد اجباری*. نام خانوادگی کاربر را بنویسید', max_length=100, verbose_name='نام خانوادگی')),
                ('NationalCode', models.CharField(db_column='کد ملی', help_text='فیلد اجباری*. کد ملی کاربر را بنویسید', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کد ملی')),
                ('BirthDate', models.DateField(blank=True, db_column='تاریخ تولد', help_text='تاریخ تولد کاربر را بنویسید', null=True, verbose_name='تاریخ تولد')),
                ('Gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], db_column='جنسیت', default='male', help_text='فیلد اجباری*. جنسیت کاربر را بنویسید', max_length=6, verbose_name='جنسیت')),
                ('About', models.CharField(blank=True, db_column='درباره من', help_text='درباره کاربر بنویسید', max_length=500, null=True, verbose_name='درباره من')),
                ('FatherName', models.CharField(blank=True, db_column='نام پدر', help_text='نام پدر کاربر را بنویسید', max_length=100, null=True, verbose_name='نام پدر')),
                ('Image', models.ImageField(blank=True, db_column='عکس', help_text='عکس کاربر را وارد کنید', null=True, upload_to='accounts/profile-images', verbose_name='عکس کاربر')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'account_CustomeUser',
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(db_column='ایمیل', help_text='ایمیل کاربر را بنویسید', max_length=254, unique=True, verbose_name='آدرس پست الکترونیکی')),
                ('Type', models.CharField(choices=[('Home', 'home'), ('Work', 'work'), ('School', 'school')], db_column='نوع ایمیل', default='Work', help_text='نوع ایمیل کاربر را بنویسید', max_length=6, verbose_name='نوع ایمیل')),
                ('Is_Default', models.BooleanField(db_column='ایمیل پیش فرض', default=False, help_text='بگویید که آیا این ایمیل پیش فرض کاربر است یا خیر', verbose_name='آیا پیش فرض است؟')),
                ('User', models.ForeignKey(blank=True, db_column='کاربر', help_text='ایمیل کدام کاربر است', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emails', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس پست الکترونیکی',
                'verbose_name_plural': 'آدرس های پست الکترونیکی',
                'db_table': 'account_EmailAddress',
                'unique_together': {('User', 'Email')},
            },
        ),
        migrations.AddField(
            model_name='customeuser',
            name='Email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounting.emailaddress', verbose_name='Gmail'),
        ),
        migrations.AlterUniqueTogether(
            name='customeuser',
            unique_together={('FirstName', 'LastName')},
        ),
    ]
