# Generated by Django 5.1.5 on 2025-01-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='DH'),
        ),
    ]
