# Generated by Django 5.1.5 on 2025-02-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='Image',
            field=models.ImageField(blank=True, db_column='عکس', help_text='عکس کاربر را وارد کنید', null=True, upload_to='Accounting/profile-images', verbose_name='عکس کاربر'),
        ),
    ]
