# Generated by Django 5.1.5 on 2025-01-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_customeuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is Active'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is Staff'),
        ),
    ]
