# Generated by Django 5.1.5 on 2025-01-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_customeuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='About',
            field=models.TextField(blank=True, db_column='درباره من', help_text='درباره کاربر بنویسید', max_length=500, null=True, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='Email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounting.emailaddress', verbose_name='Email'),
        ),
    ]
