# Generated by Django 5.1.5 on 2025-01-22 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_customeuser_about_alter_customeuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_column='نام دین', help_text='نام دین را بنویسید', max_length=50, verbose_name='عنوان دین')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'دین',
                'verbose_name_plural': 'ادیان',
                'db_table': 'Religion',
            },
        ),
        migrations.AddField(
            model_name='customeuser',
            name='Religion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Users', to='accounting.religion'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_column='سمت', help_text='عنوان سمت را بنویسید', max_length=50, verbose_name='عنوان سمت')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('User', models.ForeignKey(blank=True, help_text='سمت کدام کاربر ؟', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Roles', to=settings.AUTH_USER_MODEL, verbose_name='سمت کاربر')),
            ],
            options={
                'verbose_name': 'سمت',
                'verbose_name_plural': 'سمت ها',
                'db_table': 'Role',
            },
        ),
        migrations.AddField(
            model_name='customeuser',
            name='Role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.role'),
        ),
    ]
