# Generated by Django 5.1.5 on 2025-01-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_religion_customeuser_religion_role_customeuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='password',
            field=models.CharField(db_column='رمز عبور', help_text='لطفاً رمز عبور خود را وارد کنید.', max_length=128, verbose_name='رمز عبور'),
        ),
    ]
