# Generated by Django 5.1.5 on 2025-01-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_customeuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='User',
        ),
    ]
