# Generated by Django 5.1.5 on 2025-01-22 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_role_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_column='نام رتبه', help_text='نام رتبه را بنویسید', max_length=50, verbose_name='عنوان رتبه')),
                ('description', models.TextField(blank=True, db_column='توضیحات', help_text='توضیحات را بنویسید', max_length=500, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'رتبه',
                'verbose_name_plural': 'رتبه ها',
                'db_table': 'account_Grade',
            },
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='Email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='accounting.emailaddress', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='Role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Users', to='accounting.role'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='description',
            field=models.TextField(blank=True, db_column='توضیحات', help_text='توضیحات را بنویسید', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, db_column='توضیحات', help_text='توضیحات را بنویسید', max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterModelTable(
            name='religion',
            table='account_Religion',
        ),
        migrations.AlterModelTable(
            name='role',
            table='account_Role',
        ),
        migrations.AddField(
            model_name='customeuser',
            name='Grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Users', to='accounting.grade'),
        ),
    ]
