# Generated by Django 5.1.5 on 2025-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_grade_alter_customeuser_email_alter_customeuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='Title',
            field=models.CharField(db_column='نام رتبه', help_text='نام رتبه را بنویسید', max_length=50, unique=True, verbose_name='عنوان رتبه'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='Title',
            field=models.CharField(db_column='نام دین', help_text='نام دین را بنویسید', max_length=50, unique=True, verbose_name='عنوان دین'),
        ),
        migrations.AlterField(
            model_name='role',
            name='Title',
            field=models.CharField(db_column='سمت', help_text='عنوان سمت را بنویسید', max_length=50, unique=True, verbose_name='عنوان سمت'),
        ),
    ]
