# Generated by Django 5.1.5 on 2025-01-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_grade_title_alter_religion_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='Grade',
            field=models.OneToOneField(blank=True, db_column='رتبه', help_text='رتبه در سمت کاربر را وارد کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Users', to='accounting.grade', verbose_name='رتبه'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='Religion',
            field=models.OneToOneField(blank=True, db_column='دین', help_text='دین کاربر را وارد کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Users', to='accounting.religion', verbose_name='دین'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='Role',
            field=models.OneToOneField(blank=True, db_column='سمت', help_text='سمت کاربر را وارد کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Users', to='accounting.role', verbose_name='سمت'),
        ),
    ]
